// 该文件由AI批量生成，所有分组均为 { zh_cn, en, text } 结构
export const EXPRESSIONES = [
  { zh_cn: '笑脸', text: '😀', en: 'grinning' },
  { zh_cn: '大笑', text: '😃', en: 'smiley' },
  { zh_cn: '露齿笑', text: '😄', en: 'smile' },
  { zh_cn: '咧嘴笑', text: '😁', en: 'grin' },
  { zh_cn: '憨笑', text: '😆', en: 'laughing' },
  { zh_cn: '汗笑', text: '😅', en: 'sweat_smile' },
  { zh_cn: '喜极而泣', text: '😂', en: 'joy' },
  { zh_cn: '打滚大笑', text: '🤣', en: 'rofl' },
  { zh_cn: '感动微笑', text: '🥲', en: 'smiling_face_with_tear' },
  { zh_cn: '微笑', text: '😊', en: 'blush' },
  { zh_cn: '天使', text: '😇', en: 'innocent' },
  { zh_cn: '略带微笑', text: '🙂', en: 'slightly_smiling_face' },
  { zh_cn: '倒立脸', text: '🙃', en: 'upside_down_face' },
  { zh_cn: '眨眼', text: '😉', en: 'wink' },
  { zh_cn: '如释重负', text: '😌', en: 'relieved' },
  { zh_cn: '花痴', text: '😍', en: 'heart_eyes' },
  { zh_cn: '三颗心', text: '🥰', en: 'smiling_face_with_three_hearts' },
  { zh_cn: '飞吻', text: '😘', en: 'kissing_heart' },
  { zh_cn: '亲吻', text: '😗', en: 'kissing' },
  { zh_cn: '亲亲', text: '😙', en: 'kissing_smiling_eyes' },
  { zh_cn: '闭眼亲吻', text: '😚', en: 'kissing_closed_eyes' },
  { zh_cn: '馋嘴', text: '😋', en: 'yum' },
  { zh_cn: '吐舌', text: '😛', en: 'stuck_out_tongue' },
  { zh_cn: '闭眼吐舌', text: '😝', en: 'stuck_out_tongue_closed_eyes' },
  { zh_cn: '眨眼吐舌', text: '😜', en: 'stuck_out_tongue_winking_eye' },
  { zh_cn: '鬼脸', text: '🤪', en: 'zany_face' },
  { zh_cn: '挑眉', text: '🤨', en: 'raised_eyebrow' },
  { zh_cn: '单片眼镜', text: '🧐', en: 'monocle_face' },
  { zh_cn: '书呆子', text: '🤓', en: 'nerd_face' },
  { zh_cn: '墨镜', text: '😎', en: 'sunglasses' },
  { zh_cn: '伪装脸', text: '🥸', en: 'disguised_face' },
  { zh_cn: '星星眼', text: '🤩', en: 'star_struck' },
  { zh_cn: '派对', text: '🥳', en: 'partying_face' },
  { zh_cn: '坏笑', text: '😏', en: 'smirk' },
  { zh_cn: '不高兴', text: '😒', en: 'unamused' },
  { zh_cn: '失望', text: '😞', en: 'disappointed' },
  { zh_cn: '沉思', text: '😔', en: 'pensive' },
  { zh_cn: '担心', text: '😟', en: 'worried' },
  { zh_cn: '困惑', text: '😕', en: 'confused' },
  { zh_cn: '微皱眉', text: '🙁', en: 'slightly_frowning_face' },
  { zh_cn: '痛苦', text: '😣', en: 'persevere' },
  { zh_cn: '困扰', text: '😖', en: 'confounded' },
  { zh_cn: '疲惫', text: '😫', en: 'tired_face' },
  { zh_cn: '筋疲力尽', text: '😩', en: 'weary' },
  { zh_cn: '可怜', text: '🥺', en: 'pleading_face' },
  { zh_cn: '难过', text: '😢', en: 'cry' },
  { zh_cn: '大哭', text: '😭', en: 'sob' },
  { zh_cn: '愤怒', text: '😤', en: 'triumph' },
  { zh_cn: '生气', text: '😠', en: 'angry' },
  { zh_cn: '暴怒', text: '😡', en: 'rage' },
  { zh_cn: '咒骂', text: '🤬', en: 'cursing_face' },
  { zh_cn: '爆炸头', text: '🤯', en: 'exploding_head' },
  { zh_cn: '脸红', text: '😳', en: 'flushed' },
  { zh_cn: '中暑', text: '🥵', en: 'hot_face' },
  { zh_cn: '冻僵', text: '🥶', en: 'cold_face' },
  { zh_cn: '惊恐', text: '😱', en: 'scream' },
  { zh_cn: '害怕', text: '😨', en: 'fearful' },
  { zh_cn: '紧张', text: '😰', en: 'cold_sweat' },
  { zh_cn: '释然', text: '😥', en: 'disappointed_relieved' },
  { zh_cn: '汗', text: '😓', en: 'sweat' },
  { zh_cn: '拥抱', text: '🤗', en: 'hugs' },
  { zh_cn: '思考', text: '🤔', en: 'thinking' },
  { zh_cn: '捂嘴', text: '🤭', en: 'hand_over_mouth' },
  { zh_cn: '嘘', text: '🤫', en: 'shushing_face' },
  { zh_cn: '说谎', text: '🤥', en: 'lying_face' },
  { zh_cn: '无语', text: '😶', en: 'no_mouth' },
  { zh_cn: '冷漠', text: '😐', en: 'neutral_face' },
  { zh_cn: '无表情', text: '😑', en: 'expressionless' },
  { zh_cn: '扭曲', text: '😬', en: 'grimacing' },
  { zh_cn: '翻白眼', text: '🙄', en: 'roll_eyes' },
  { zh_cn: '惊讶', text: '😯', en: 'hushed' },
  { zh_cn: '失望', text: '😦', en: 'frowning' },
  { zh_cn: '痛苦', text: '😧', en: 'anguished' },
  { zh_cn: '吃惊', text: '😮', en: 'open_mouth' },
  { zh_cn: '震惊', text: '😲', en: 'astonished' },
  { zh_cn: '打哈欠', text: '🥱', en: 'yawning_face' },
  { zh_cn: '睡觉', text: '😴', en: 'sleeping' },
  { zh_cn: '流口水', text: '🤤', en: 'drooling_face' },
  { zh_cn: '困', text: '😪', en: 'sleepy' },
  { zh_cn: '晕', text: '😵', en: 'dizzy_face' },
  { zh_cn: '拉链嘴', text: '🤐', en: 'zipper_mouth_face' },
  { zh_cn: '迷糊', text: '🥴', en: 'woozy_face' },
  { zh_cn: '恶心', text: '🤢', en: 'nauseated_face' },
  { zh_cn: '呕吐', text: '🤮', en: 'vomiting_face' },
  { zh_cn: '打喷嚏', text: '🤧', en: 'sneezing_face' },
  { zh_cn: '口罩', text: '😷', en: 'mask' },
  { zh_cn: '生病', text: '🤒', en: 'face_with_thermometer' },
  { zh_cn: '受伤', text: '🤕', en: 'face_with_head_bandage' },
  { zh_cn: '发财', text: '🤑', en: 'money_mouth_face' },
  { zh_cn: '牛仔', text: '🤠', en: 'cowboy_hat_face' },
  { zh_cn: '小恶魔', text: '😈', en: 'smiling_imp' },
  { zh_cn: '恶魔', text: '👿', en: 'imp' },
  { zh_cn: '鬼怪', text: '👹', en: 'japanese_ogre' },
  { zh_cn: '妖怪', text: '👺', en: 'japanese_goblin' },
  { zh_cn: '小丑', text: '🤡', en: 'clown_face' },
  { zh_cn: '便便', text: '💩', en: 'poop' },
  { zh_cn: '幽灵', text: '👻', en: 'ghost' },
  { zh_cn: '骷髅', text: '💀', en: 'skull' },
  { zh_cn: '骷髅交叉骨', text: '☠️', en: 'skull_and_crossbones' },
  { zh_cn: '外星人', text: '👽', en: 'alien' },
  { zh_cn: '入侵者', text: '👾', en: 'space_invader' },
  { zh_cn: '机器人', text: '🤖', en: 'robot' },
  { zh_cn: '南瓜灯', text: '🎃', en: 'jack_o_lantern' },
  { zh_cn: '猫脸', text: '😺', en: 'smiley_cat' },
  { zh_cn: '猫笑', text: '😸', en: 'smile_cat' },
  { zh_cn: '猫喜极而泣', text: '😹', en: 'joy_cat' },
  { zh_cn: '猫花痴', text: '😻', en: 'heart_eyes_cat' },
  { zh_cn: '猫坏笑', text: '😼', en: 'smirk_cat' },
  { zh_cn: '猫亲吻', text: '😽', en: 'kissing_cat' },
  { zh_cn: '猫惊恐', text: '🙀', en: 'scream_cat' },
  { zh_cn: '猫哭', text: '😿', en: 'crying_cat_face' },
  { zh_cn: '猫生气', text: '😾', en: 'pouting_cat' },
]
// 其余分组 GESTURES、SYMBOLS、OBJECTS、ACTIVITIES、SKY_WEATHER 可按同样结构补全
// 本文件为 emoji 数据，分组数据结构，便于 emoji 选择器使用
// 下面为 GESTURES（手势）分组示例，可按需继续补充其他分组

export const GESTURES = [
  { zh_cn: '挥手', text: '👋', en: 'wave' },
  { zh_cn: '点赞', text: '👍', en: 'thumbs_up' },
  { zh_cn: '点踩', text: '👎', en: 'thumbs_down' },
  { zh_cn: '拳头', text: '👊', en: 'fist_oncoming' },
  { zh_cn: '举手', text: '✋', en: 'raised_hand' },
  { zh_cn: '胜利', text: '✌️', en: 'v' },
  { zh_cn: 'OK', text: '👌', en: 'ok_hand' },
  { zh_cn: '合十', text: '🙏', en: 'pray' },
  { zh_cn: '握手', text: '🤝', en: 'handshake' },
  { zh_cn: '鼓掌', text: '👏', en: 'clap' },
  { zh_cn: '指向右', text: '👉', en: 'point_right' },
  { zh_cn: '指向左', text: '👈', en: 'point_left' },
  { zh_cn: '指向上', text: '👆', en: 'point_up_2' },
  { zh_cn: '指向下', text: '👇', en: 'point_down' },
  { zh_cn: '举起双手', text: '🙌', en: 'raised_hands' },
  { zh_cn: '捏手指', text: '🤏', en: 'pinching_hand' },
  { zh_cn: '比心', text: '🫶', en: 'heart_hands' },
  { zh_cn: '竖中指', text: '🖕', en: 'middle_finger' },
  { zh_cn: '握拳', text: '✊', en: 'fist_raised' },
  { zh_cn: '手指交叉', text: '🤞', en: 'fingers_crossed' },
  { zh_cn: '手指圈', text: '🫰', en: 'hand_with_index_finger_and_thumb_crossed' },
  { zh_cn: '敬礼', text: '🫡', en: 'saluting_face' },
]
/**
 * @Description: 符号、物体、运动、天气分组 emoji 数据
 * @Author: ykx
 * @Date: 2022-12-02
 */

// 符号分组
export const SYMBOLS = [
  { zh_cn: '红心', text: '❤️', en: 'heart' },
  { zh_cn: '橙心', text: '🧡', en: 'orange_heart' },
  { zh_cn: '黄心', text: '💛', en: 'yellow_heart' },
  { zh_cn: '绿心', text: '💚', en: 'green_heart' },
  { zh_cn: '蓝心', text: '💙', en: 'blue_heart' },
  { zh_cn: '紫心', text: '💜', en: 'purple_heart' },
  { zh_cn: '黑心', text: '🖤', en: 'black_heart' },
  { zh_cn: '白心', text: '🤍', en: 'white_heart' },
  { zh_cn: '破碎的心', text: '💔', en: 'broken_heart' },
  { zh_cn: '星星', text: '⭐', en: 'star' },
  { zh_cn: '闪烁星', text: '✨', en: 'sparkles' },
  { zh_cn: '火焰', text: '🔥', en: 'fire' },
  { zh_cn: '水滴', text: '💧', en: 'droplet' },
  { zh_cn: '雪花', text: '❄️', en: 'snowflake' },
  { zh_cn: '太阳', text: '☀️', en: 'sun' },
  { zh_cn: '月亮', text: '🌙', en: 'crescent_moon' },
  { zh_cn: '音符', text: '🎵', en: 'musical_note' },
  { zh_cn: '闪电', text: '⚡', en: 'zap' },
  { zh_cn: '问号', text: '❓', en: 'question' },
  { zh_cn: '感叹号', text: '❗', en: 'exclamation' },
  { zh_cn: '对勾', text: '✔️', en: 'heavy_check_mark' },
  { zh_cn: '叉号', text: '❌', en: 'x' },
  { zh_cn: '警告', text: '⚠️', en: 'warning' },
  { zh_cn: '禁止', text: '🚫', en: 'no_entry_sign' },
]

// 物体分组
export const OBJECTS = [
  { zh_cn: '礼物', text: '🎁', en: 'gift' },
  { zh_cn: '气球', text: '🎈', en: 'balloon' },
  { zh_cn: '蛋糕', text: '🎂', en: 'birthday' },
  { zh_cn: '相机', text: '📷', en: 'camera' },
  { zh_cn: '电话', text: '☎️', en: 'telephone' },
  { zh_cn: '电脑', text: '💻', en: 'computer' },
  { zh_cn: '灯泡', text: '💡', en: 'bulb' },
  { zh_cn: '书', text: '📚', en: 'books' },
  { zh_cn: '信封', text: '✉️', en: 'envelope' },
  { zh_cn: '钥匙', text: '🔑', en: 'key' },
  { zh_cn: '锁', text: '🔒', en: 'lock' },
  { zh_cn: '剪刀', text: '✂️', en: 'scissors' },
  { zh_cn: '雨伞', text: '☂️', en: 'umbrella' },
  { zh_cn: '时钟', text: '⏰', en: 'alarm_clock' },
  { zh_cn: '钱包', text: '👛', en: 'purse' },
  { zh_cn: '购物袋', text: '🛍️', en: 'shopping_bags' },
  { zh_cn: '药丸', text: '💊', en: 'pill' },
  { zh_cn: '注射器', text: '💉', en: 'syringe' },
  { zh_cn: '锤子', text: '🔨', en: 'hammer' },
  { zh_cn: '齿轮', text: '⚙️', en: 'gear' },
]

// 运动分组
export const ACTIVITIES = [
  { zh_cn: '足球', text: '⚽', en: 'soccer' },
  { zh_cn: '篮球', text: '🏀', en: 'basketball' },
  { zh_cn: '排球', text: '🏐', en: 'volleyball' },
  { zh_cn: '棒球', text: '⚾', en: 'baseball' },
  { zh_cn: '网球', text: '🎾', en: 'tennis' },
  { zh_cn: '乒乓球', text: '🏓', en: 'ping_pong' },
  { zh_cn: '羽毛球', text: '🏸', en: 'badminton' },
  { zh_cn: '高尔夫', text: '⛳', en: 'golf' },
  { zh_cn: '跑步', text: '🏃', en: 'runner' },
  { zh_cn: '游泳', text: '🏊', en: 'swimmer' },
  { zh_cn: '骑自行车', text: '🚴', en: 'bicyclist' },
  { zh_cn: '滑雪', text: '⛷️', en: 'skier' },
  { zh_cn: '冲浪', text: '🏄', en: 'surfer' },
  { zh_cn: '举重', text: '🏋️', en: 'weight_lifter' },
  { zh_cn: '瑜伽', text: '🧘', en: 'lotus_position' },
  { zh_cn: '拳击', text: '🥊', en: 'boxing_glove' },
  { zh_cn: '奖杯', text: '🏆', en: 'trophy' },
  { zh_cn: '奖牌', text: '🏅', en: 'medal' },
  { zh_cn: '旗帜', text: '🚩', en: 'triangular_flag' },
]

// 天气分组
export const SKY_WEATHER = [
  { zh_cn: '晴天', text: '☀️', en: 'sunny' },
  { zh_cn: '多云', text: '⛅', en: 'partly_sunny' },
  { zh_cn: '阴天', text: '☁️', en: 'cloud' },
  { zh_cn: '下雨', text: '🌧️', en: 'cloud_with_rain' },
  { zh_cn: '下雪', text: '🌨️', en: 'cloud_with_snow' },
  { zh_cn: '雷雨', text: '⛈️', en: 'cloud_with_lightning_and_rain' },
  { zh_cn: '闪电', text: '🌩️', en: 'cloud_with_lightning' },
  { zh_cn: '雾', text: '🌫️', en: 'fog' },
  { zh_cn: '风', text: '🌬️', en: 'wind_face' },
  { zh_cn: '彩虹', text: '🌈', en: 'rainbow' },
  { zh_cn: '新月', text: '🌙', en: 'crescent_moon' },
  { zh_cn: '星星', text: '⭐', en: 'star' },
  { zh_cn: '雪花', text: '❄️', en: 'snowflake' },
  { zh_cn: '水滴', text: '💧', en: 'droplet' },
  { zh_cn: '伞', text: '☂️', en: 'umbrella' },
]
