import { getKnowledgeKit } from '@st/extensions/kit'
import type { EditorPreset } from './types'

export const knowledgePreset: EditorPreset = {
  name: 'knowledge',
  getExtensions: (props) => getKnowledgeKit(props),
  toolbar: [
    'insert',
    '|',
    'undo', 'redo', 'format-painter', 'clearNodeAndMarks',
    '|',
    'heading', 'fontSize',
    '|',
    'bold', 'italic', 'underline', 'strike', 'moreText',
    '|',
    'textColor', 'backgroundColor',
    '|',
    'link',
    '|',
    'align',
    '|',
    'bulletList', 'orderedList', 'taskList',
    '|',
    'indent',
    '|',
    'emoji',
    '|',
    'blockquote', 'horizontalRule',
    '|',
    'findAndReplace',
    '|',
    'import',
    'export',
  ],
  bubbleMenus: ['text', 'tag', 'image', 'attachment', 'table', 'callout', 'drag'],
  features: {
    hasTitle: true,
    hasDragHandle: true,
    contentMode: 'json',
    showDocumentSuggest: true,
    showSearchReplace: true,
  },
}
