/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAnchor: typeof import('ant-design-vue/es')['Anchor']
    AAnchorLink: typeof import('ant-design-vue/es')['AnchorLink']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopover: typeof import('ant-design-vue/es')['Popover']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    BgColorsOutlined: typeof import('@ant-design/icons-vue')['BgColorsOutlined']
    BoldOutlined: typeof import('@ant-design/icons-vue')['BoldOutlined']
    CaretRightOutlined: typeof import('@ant-design/icons-vue')['CaretRightOutlined']
    CheckOutlined: typeof import('@ant-design/icons-vue')['CheckOutlined']
    DownloadOutlined: typeof import('@ant-design/icons-vue')['DownloadOutlined']
    MenuFoldOutlined: typeof import('@ant-design/icons-vue')['MenuFoldOutlined']
    MenuUnfoldOutlined: typeof import('@ant-design/icons-vue')['MenuUnfoldOutlined']
    PlusOutlined: typeof import('@ant-design/icons-vue')['PlusOutlined']
    ProfileOutlined: typeof import('@ant-design/icons-vue')['ProfileOutlined']
    RedoOutlined: typeof import('@ant-design/icons-vue')['RedoOutlined']
    RightOutlined: typeof import('@ant-design/icons-vue')['RightOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    StrikeOutlined: typeof import('@ant-design/icons-vue')['StrikeOutlined']
    StrikethroughOutlined: typeof import('@ant-design/icons-vue')['StrikethroughOutlined']
    UndoOutlined: typeof import('@ant-design/icons-vue')['UndoOutlined']
  }
}
