/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ASpace: typeof import('ant-design-vue/es')['Space']
    CaretDownOutlined: typeof import('@ant-design/icons-vue')['CaretDownOutlined']
    CaretUpOutlined: typeof import('@ant-design/icons-vue')['CaretUpOutlined']
    CopyOutlined: typeof import('@ant-design/icons-vue')['CopyOutlined']
  }
}
