/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AInput: typeof import('ant-design-vue/es')['Input']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BasePluginBox: typeof import('./components/wrappers/BasePluginBox.vue')['default']
    CenterLoading: typeof import('./components/basic/centerLoading/index.vue')['default']
    ColorPicker: typeof import('./components/colorPicker/index.vue')['default']
    CommonMenu: typeof import('./components/commonMenu/index.vue')['default']
    DocExportModal: typeof import('./components/modal/DocExportModal.vue')['default']
    DocItem: typeof import('./components/docItem/index.vue')['default']
    DocShareConfirmModal: typeof import('./components/modal/DocShareConfirmModal.vue')['default']
    DraggableModal: typeof import('./components/basic/draggable-modal/index.vue')['default']
    EmojiPicker: typeof import('./components/emojiPicker/index.vue')['default']
    FileSearchOutlined: typeof import('@ant-design/icons-vue')['FileSearchOutlined']
    Index: typeof import('./components/document/editor/Index.vue')['default']
    KeyMapTip: typeof import('./components/basic/keyMapTip/index.vue')['default']
    LayoutLogo: typeof import('./components/layoutLogo/index.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Message: typeof import('./components/message/index.vue')['default']
    Resizeable: typeof import('./components/basic/resizeable/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchReplaceModal: typeof import('./components/searchReplaceModal/index.vue')['default']
    ShortcutGuideModal: typeof import('./components/modal/ShortcutGuideModal.vue')['default']
    SpeedTooltip: typeof import('./components/SpeedTooltip/index.vue')['default']
    TemplateItem: typeof import('./components/templateItem/index.vue')['default']
    TitleView: typeof import('./components/titleView/titleView.vue')['default']
    TplPreviewModal: typeof import('./components/tplPreviewModal/index.vue')['default']
    WikiItem: typeof import('./components/wikiItem/index.vue')['default']
    WikiUserModal: typeof import('./components/modal/WikiUserModal.vue')['default']
  }
}
