/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAnchor: typeof import('ant-design-vue/es')['Anchor']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopover: typeof import('ant-design-vue/es')['Popover']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    CaretDownOutlined: typeof import('@ant-design/icons-vue')['CaretDownOutlined']
    CaretRightOutlined: typeof import('@ant-design/icons-vue')['CaretRightOutlined']
    CheckOutlined: typeof import('@ant-design/icons-vue')['CheckOutlined']
    ClearOutlined: typeof import('@ant-design/icons-vue')['ClearOutlined']
    CopyOutlined: typeof import('@ant-design/icons-vue')['CopyOutlined']
    DeleteOutlined: typeof import('@ant-design/icons-vue')['DeleteOutlined']
    DownloadOutlined: typeof import('@ant-design/icons-vue')['DownloadOutlined']
    EnterOutlined: typeof import('@ant-design/icons-vue')['EnterOutlined']
    FileSearchOutlined: typeof import('@ant-design/icons-vue')['FileSearchOutlined']
    FormatPainterOutlined: typeof import('@ant-design/icons-vue')['FormatPainterOutlined']
    RedoOutlined: typeof import('@ant-design/icons-vue')['RedoOutlined']
    RightOutlined: typeof import('@ant-design/icons-vue')['RightOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UndoOutlined: typeof import('@ant-design/icons-vue')['UndoOutlined']
  }
}
